capstone_snowflake:
  target: dev

  outputs:
    dev:
      type: snowflake
      account: DVWPLES-MZB77847
      user: TAMANNAMALVIYA
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: SYSADMIN
      database: CAPSTONE_DB
      schema: RAW
      warehouse: ANALYTICS_WH
      threads: 4
