{{ config(
    schema = 'CORE',
    materialized = 'incremental',
    unique_key = 'PAYMENT_SK',
    incremental_strategy = 'merge'
) }}

SELECT
    MD5(CONCAT(UPPER(TRIM(PAYMENT_CHANNEL)),'|',UPPER(TRIM(PAYMENT_METHOD)))) AS PAYMENT_SK,
    UPPER(TRIM(PAYMENT_CHANNEL)) AS PAYMENT_CHANNEL,
    UPPER(TRIM(PAYMENT_METHOD)) AS PAYMENT_METHOD
FROM {{ ref('stg_banking_data') }}
WHERE PAYMENT_CHANNEL IS NOT NULL AND PAYMENT_METHOD IS NOT NULL
QUALIFY ROW_NUMBER() OVER (PARTITION BY UPPER(TRIM(PAYMENT_CHANNEL)),UPPER(TRIM(PAYMENT_METHOD))ORDER BY _LOADED_AT DESC) = 1