{{ config (schema = 'MART',
           materialized = 'view')}}

SELECT
    b.BRANCH_NAME,
    c.COMPLAINT_CATEGORY,
    COUNT(DISTINCT c.COMPLAINT_ID) AS TOTAL_COMPLAINTS,
    COUNT(DISTINCT CASE WHEN UPPER(TRIM(c.COMPLAINT_STATUS)) = 'RESOLVED' THEN c.COMPLAINT_ID END) AS RESOLVED_COMPLAINTS,
    ROUND( COUNT(DISTINCT CASE WHEN UPPER(TRIM(c.COMPLAINT_STATUS)) = 'RESOLVED' THEN c.COMPLAINT_ID END) * 100.0 
    / NULLIF(COUNT(DISTINCT c.COMPLAINT_ID), 0), 2) AS RESOLUTION_RATE
FROM (
    SELECT DISTINCT
        BRANCH_ID,
        COMPLAINT_ID
    FROM {{ ref ('fact_transaction') }}
    WHERE COMPLAINT_ID IS NOT NULL AND COMPLAINT_ID <> 'N/A'
) t
JOIN {{ ref ('dim_branch') }} AS b ON t.BRANCH_ID = b.BRANCH_ID
JOIN {{ ref ('dim_complaint') }} AS c ON t.COMPLAINT_ID = c.COMPLAINT_ID
GROUP BY b.BRANCH_NAME, c.COMPLAINT_CATEGORY
ORDER BY b.BRANCH_NAME, c.COMPLAINT_CATEGORY