{{ config (schema = 'MART',
           materialized = 'view')}}

SELECT b.BRANCH_NAME,
       COUNT_IF(c.COMPLAINT_PRIORITY = 'CRITICAL') AS CRITICAL_PRIORITY_COMPLAINT,
       COUNT_IF(c.COMPLAINT_PRIORITY = 'HIGH') AS HIGH_PRIORITY_COMPLAINT,
       COUNT_IF(c.COMPLAINT_PRIORITY = 'MEDIUM') AS MEDIUM_PRIORITY_COMPLAINT,
       COUNT_IF(c.COMPLAINT_PRIORITY = 'LOW') AS LOW_PRIORITY_COMPLAINT
FROM (SELECT DISTINCT BRANCH_ID,
             COMPLAINT_ID
      FROM {{ ref ('fact_transaction') }}
      WHERE COMPLAINT_ID IS NOT NULL) t
JOIN {{ ref ('dim_branch') }} AS b ON t.BRANCH_ID = b.BRANCH_ID
JOIN {{ ref ('dim_complaint') }} AS c ON t.COMPLAINT_ID = c.COMPLAINT_ID
GROUP BY b.BRANCH_NAME