{{ config (schema = 'MART',
           materialized = 'view')}}

SELECT LOAN_TYPE,
       COUNT(*) AS LOAN_COUNT,
       SUM(LOAN_AMOUNT) AS TOTAL_LOAN_EXPOSURE,
       ROUND(AVG(INTEREST_RATE), 2) AS AVG_INTEREST_RATE,
       ROUND(AVG(TENURE_MONTHS), 2) AS AVG_TENURE_MONTH,
       ROUND(SUM(LOAN_AMOUNT * INTEREST_RATE * TENURE_MONTHS) / 12, 2) AS ESTIMATED_INTEREST
FROM {{ ref ('dim_loan') }}
GROUP BY LOAN_TYPE
ORDER BY ESTIMATED_INTEREST DESC
