{{ config (schema = 'MART',
           materialized = 'view')}}

WITH CTE AS (SELECT DATE_TRUNC('MONTH', TRANSACTION_DATE) AS TRANSACTION_MONTH,
       SUM(AMOUNT) AS TOTAL_TRANSACTION_VALUE
FROM {{ ref ('fact_transaction') }}
GROUP BY DATE_TRUNC('MONTH', TRANSACTION_DATE)),

CTE2 AS (SELECT *, 
         LAG(TOTAL_TRANSACTION_VALUE) OVER (ORDER BY TRANSACTION_MONTH) AS PREVIOUS_MONTH_VALUE
         FROM CTE)
SELECT TRANSACTION_MONTH,
       TOTAL_TRANSACTION_VALUE,
       PREVIOUS_MONTH_VALUE,
       ROUND((TOTAL_TRANSACTION_VALUE - PREVIOUS_MONTH_VALUE) / NULLIF(PREVIOUS_MONTH_VALUE, 0) * 100.0, 2) AS MOM_GROWTH_PERCENTAGE
FROM CTE2
ORDER BY TRANSACTION_MONTH