{{ config (schema = 'MART',
           materialized = 'view')}}

SELECT
    b.BRANCH_NAME,
    l.LOAN_TYPE,
    COUNT(DISTINCT l.LOAN_ID) AS TOTAL_SUBPRIME_LOANS,
    COUNT(DISTINCT CASE WHEN UPPER(TRIM(l.LOAN_STATUS)) = 'DELINQUENT' THEN l.LOAN_ID END) AS DEFAULTED_LOANS,
    ROUND(COUNT(DISTINCT CASE WHEN UPPER(TRIM(l.LOAN_STATUS)) = 'DELINQUENT' THEN l.LOAN_ID END) * 100.0 / NULLIF(COUNT(DISTINCT l.LOAN_ID), 0), 2) AS DEFAULT_RATE_PERCENT
FROM {{ ref ('fact_transaction') }} AS t
JOIN {{ ref ('dim_customers') }} AS c ON t.CUSTOMER_ID = c.CUSTOMER_ID
JOIN {{ ref ('dim_loan') }} AS l ON t.LOAN_ID = l.LOAN_ID
JOIN {{ ref ('dim_branch') }} AS b ON t.BRANCH_ID = b.BRANCH_ID
WHERE c.CREDIT_SCORE < 650
  AND t.TRANSACTION_DATE >= '2026-04-01'
  AND t.TRANSACTION_DATE < '2026-07-01'
  AND t.LOAN_ID IS NOT NULL
  AND t.LOAN_ID <> 'N/A'
GROUP BY b.BRANCH_NAME, l.LOAN_TYPE
ORDER BY b.BRANCH_NAME, l.LOAN_TYPE