{{ config (schema = 'MART',
           materialized = 'view')}}

WITH CTE AS (SELECT p.PAYMENT_CHANNEL,
       COUNT(t.*) AS TRANSACTION_COUNT,
       COUNT_IF(t.TRANSACTION_STATUS = 'SUCCESS') AS SUCCESS_TRANSACTIONS
FROM {{ ref ('fact_transaction') }} AS t
JOIN {{ ref ('dim_payments') }} AS p ON p.PAYMENT_SK = t.PAYMENT_SK
GROUP BY p.PAYMENT_CHANNEL) 

SELECT PAYMENT_CHANNEL,
       TRANSACTION_COUNT,
       SUCCESS_TRANSACTIONS,
       SUCCESS_TRANSACTIONS / TRANSACTION_COUNT * 100.0 AS SUCCESS_RATE
FROM CTE
