{{ config (schema = 'MART',
           materialized = 'view')}}

WITH CTE1 AS (
SELECT b.BRANCH_ID,
       b.BRANCH_NAME,
       DATE_TRUNC('MONTH', t.TRANSACTION_DATE) AS TRANSACTION_MONTH,
       COUNT(t.*) AS TRANSACTION_COUNT,
       SUM(t.AMOUNT) AS TOTAL_TRANSACTION_AMOUNT
FROM {{ ref ('fact_transaction') }} AS t
JOIN {{ ref ('dim_branch') }} AS b ON t.BRANCH_ID = b.BRANCH_ID
GROUP BY 1, 2, 3
),

CTE2 AS (
SELECT *,
       LAG(TOTAL_TRANSACTION_AMOUNT) OVER (PARTITION BY BRANCH_ID ORDER BY TRANSACTION_MONTH) AS PREVIOUS_TRANSACTION_AMOUNT,
       RANK() OVER (PARTITION BY TRANSACTION_MONTH ORDER BY TOTAL_TRANSACTION_AMOUNT DESC) AS RANK_BY_AMOUNT
FROM CTE1
)

SELECT 
    BRANCH_ID,
    BRANCH_NAME,
    TRANSACTION_MONTH,
    TRANSACTION_COUNT,
    TOTAL_TRANSACTION_AMOUNT,
    PREVIOUS_TRANSACTION_AMOUNT,
    ROUND(((TOTAL_TRANSACTION_AMOUNT - PREVIOUS_TRANSACTION_AMOUNT) / NULLIF(PREVIOUS_TRANSACTION_AMOUNT, 0)) * 100, 2) AS MOM_GROWTH_PERCENTAGE,
    RANK_BY_AMOUNT
FROM CTE2