{{ config (schema = 'MART',
           materialized = 'view')}}

WITH CTE1 AS (
    SELECT
        c.CUSTOMER_ID,
        c.CUSTOMER_NAME,
        c.CUSTOMER_SEGMENT,
        DATE_TRUNC('MONTH', t.TRANSACTION_DATE) AS TRANSACTION_MONTH,
        SUM(t.AMOUNT) AS CURRENT_MONTH_AMOUNT
    FROM {{ ref ('fact_transaction') }} AS t
    JOIN {{ ref ('dim_customers') }} AS c ON t.CUSTOMER_ID = c.CUSTOMER_ID
    GROUP BY c.CUSTOMER_ID, c.CUSTOMER_NAME, c.CUSTOMER_SEGMENT, DATE_TRUNC('MONTH', t.TRANSACTION_DATE)),

CTE2 AS (
    SELECT
        *,
        LAG(CURRENT_MONTH_AMOUNT) OVER (PARTITION BY CUSTOMER_ID ORDER BY TRANSACTION_MONTH) AS PREVIOUS_MONTH_AMOUNT,
        LEAD(CURRENT_MONTH_AMOUNT) OVER (PARTITION BY CUSTOMER_ID ORDER BY TRANSACTION_MONTH) AS NEXT_MONTH_AMOUNT
    FROM CTE1),

CTE3 AS (
    SELECT
        *,
        ROUND(((CURRENT_MONTH_AMOUNT - PREVIOUS_MONTH_AMOUNT) / NULLIF(PREVIOUS_MONTH_AMOUNT, 0)) * 100, 2) AS MOM_GROWTH_PERCENTAGE,
        DENSE_RANK() OVER (PARTITION BY CUSTOMER_SEGMENT, TRANSACTION_MONTH ORDER BY CURRENT_MONTH_AMOUNT DESC) AS CUSTOMER_RANK_WITHIN_SEGMENT
    FROM CTE2)

SELECT * FROM CTE3
ORDER BY CUSTOMER_ID, TRANSACTION_MONTH