{{ config (schema = 'MART',
           materialized = 'view')}}

SELECT COUNT(*) AS TRANSACTION_COUNT,
       SUM(AMOUNT) AS TOTAL_TRANSACTION_AMOUNT,
       ROUND(AVG(AMOUNT), 2) AS AVG_TRANSACTION_AMOUNT,
       COUNT_IF(TRANSACTION_STATUS = 'SUCCESS') AS SUCCESSFUL_TRANSACTION_COUNT,
       COUNT_IF(TRANSACTION_STATUS = 'FAILED') AS FAILED_TRANACTION_COUNT,
       COUNT_IF(IS_FLAGGED_FRAUD = 'TRUE') AS FRAUD_COUNT,
       SUM(CASE WHEN IS_FLAGGED_FRAUD = 'TRUE' THEN AMOUNT ELSE 0 END) AS FRAUD_AMOUNT,
       ROUND(COUNT_IF(TRANSACTION_STATUS = 'SUCCESS') * 100.0 / NULLIF(COUNT(TRANSACTION_ID), 0), 2) AS SUCCESS_RATE

FROM {{ ref ('fact_transaction') }}