{{ config (schema = 'STAGING',
           materialized = 'view')}}

WITH source_data AS (
    SELECT 
        TRANSACTION_ID,
        TRANSACTION_DATE,
        TRANSACTION_TYPE,
        AMOUNT,
        CURRENCY,
        TRANSACTION_STATUS,
        PAYMENT_CHANNEL,
        PAYMENT_METHOD,
        RUNNING_BALANCE,
        IS_FLAGGED_FRAUD,
        MERCHANT_NAME,
        MERCHANT_CATEGORY,
        CUSTOMER_ID,
        CUSTOMER_NAME,
        CUSTOMER_DOB,
        CUSTOMER_GENDER,
        CUSTOMER_EMAIL,
        CUSTOMER_PHONE,
        CUSTOMER_CITY,
        CUSTOMER_COUNTRY,
        CUSTOMER_SEGMENT,
        KYC_STATUS,
        CUSTOMER_ANNUAL_INCOME,
        CREDIT_SCORE,
        ACCOUNT_ID,
        ACCOUNT_TYPE,
        ACCOUNT_OPEN_DATE,
        ACCOUNT_STATUS,
        BRANCH_ID,
        BRANCH_NAME,
        CREDIT_CARD_ID,
        CARD_TYPE,
        CARD_NETWORK,
        CREDIT_LIMIT,
        CARD_STATUS,
        LOAN_ID,
        LOAN_TYPE,
        LOAN_AMOUNT,
        INTEREST_RATE,
        TENURE_MONTHS,
        LOAN_STATUS,
        COMPLAINT_ID,
        COMPLAINT_CATEGORY,
        COMPLAINT_PRIORITY,
        COMPLAINT_STATUS,
        _LOADED_AT
    FROM {{ source ('raw', 'raw_banking_data')}}
)

SELECT 
  TRIM(TRANSACTION_ID) AS TRANSACTION_ID,
COALESCE(
    TRY_TO_DATE(TRIM(TRANSACTION_DATE), 'MM/DD/YYYY'),
    TRY_TO_DATE(TRIM(TRANSACTION_DATE), 'MM-DD-YYYY'),
    TRY_TO_DATE(TRIM(TRANSACTION_DATE), 'DD-MM-YYYY'),
    TRY_TO_TIMESTAMP_NTZ(TRIM(TRANSACTION_DATE))::DATE
) AS TRANSACTION_DATE,
  TRIM(TRANSACTION_TYPE) AS TRANSACTION_TYPE,
  TRY_TO_NUMBER(AMOUNT, 12, 2) AS AMOUNT,
  UPPER(TRIM(CURRENCY)) AS CURRENCY,
  UPPER(TRIM(TRANSACTION_STATUS)) AS TRANSACTION_STATUS,
  UPPER(TRIM(PAYMENT_CHANNEL)) AS PAYMENT_CHANNEL,
  UPPER(TRIM(PAYMENT_METHOD)) AS PAYMENT_METHOD,
  TRY_TO_DECIMAL(TRIM(RUNNING_BALANCE)) AS RUNNING_BALANCE,
  CASE WHEN UPPER(TRIM(IS_FLAGGED_FRAUD)) IN ('TRUE', 'Y', 'YES', '1')  
       THEN TRUE
       WHEN UPPER(TRIM(IS_FLAGGED_FRAUD)) IN ('FALSE', 'NO', 'N', '0')
       THEN FALSE
  END AS IS_FLAGGED_FRAUD,
  TRIM(MERCHANT_NAME) AS MERCHANT_NAME,
  TRIM(MERCHANT_CATEGORY) AS MERCHANT_CATEGORY,
  TRIM(CUSTOMER_ID) AS CUSTOMER_ID,
  TRIM(CUSTOMER_NAME) AS CUSTOMER_NAME,
COALESCE(
    TRY_TO_DATE(TRIM(CUSTOMER_DOB), 'MM/DD/YYYY'),
    TRY_TO_DATE(TRIM(CUSTOMER_DOB), 'MM-DD-YYYY'),
    TRY_TO_DATE(TRIM(CUSTOMER_DOB), 'DD-MM-YYYY'),
    TRY_TO_TIMESTAMP_NTZ(TRIM(CUSTOMER_DOB))::DATE
) AS CUSTOMER_DOB,
  CASE WHEN CUSTOMER_GENDER = 'M' 
       THEN 'MALE'
       WHEN CUSTOMER_GENDER = 'F'
       THEN 'FEMALE'
       ELSE 'OTHER'
  END AS CUSTOMER_GENDER,
  LOWER(TRIM(CUSTOMER_EMAIL)) AS CUSTOMER_EMAIL,
  TRY_CAST(CUSTOMER_PHONE AS INTEGER) AS CUSTOMER_PHONE,
  INITCAP(TRIM(CUSTOMER_CITY)) AS CUSTOMER_CITY,
  INITCAP(TRIM(CUSTOMER_COUNTRY)) AS CUSTOMER_COUNTRY,
  UPPER(TRIM(CUSTOMER_SEGMENT)) AS CUSTOMER_SEGMENT,
  UPPER(TRIM(KYC_STATUS)) AS KYC_STATUS,
  TRY_TO_DECIMAL(CUSTOMER_ANNUAL_INCOME, 18, 2) AS CUSTOMER_ANNUAL_INCOME,
  TRY_CAST(CREDIT_SCORE AS INTEGER) AS CREDIT_SCORE,
  TRIM(ACCOUNT_ID) AS ACCOUNT_ID,
  UPPER(TRIM(ACCOUNT_TYPE)) AS ACCOUNT_TYPE,
COALESCE(
    TRY_TO_DATE(TRIM(ACCOUNT_OPEN_DATE), 'MM/DD/YYYY'),
    TRY_TO_DATE(TRIM(ACCOUNT_OPEN_DATE), 'MM-DD-YYYY'),
    TRY_TO_DATE(TRIM(ACCOUNT_OPEN_DATE), 'DD-MM-YYYY'),
    TRY_TO_TIMESTAMP_NTZ(TRIM(ACCOUNT_OPEN_DATE))::DATE
) AS ACCOUNT_OPEN_DATE,
  UPPER(TRIM(ACCOUNT_STATUS)) AS ACCOUNT_STATUS,
  TRIM(BRANCH_ID) AS BRANCH_ID,
  TRIM(BRANCH_NAME) AS BRANCH_NAME,
  TRIM(CREDIT_CARD_ID) AS CREDIT_CARD_ID,
  UPPER(TRIM(CARD_TYPE)) AS CARD_TYPE,
  UPPER(TRIM(CARD_NETWORK)) AS CARD_NETWORK,
  TRY_TO_DECIMAL(CREDIT_LIMIT, 18, 2) AS CREDIT_LIMIT,
  UPPER(TRIM(CARD_STATUS)) AS CARD_STATUS,
  TRIM(LOAN_ID) AS LOAN_ID,
  UPPER(TRIM(LOAN_TYPE)) AS LOAN_TYPE,
  TRY_TO_DECIMAL(LOAN_AMOUNT, 18, 2) AS LOAN_AMOUNT,
  TRY_TO_DECIMAL(INTEREST_RATE, 10, 2) AS INTEREST_RATE,
  TRY_CAST(TENURE_MONTHS AS INTEGER) AS TENURE_MONTHS,
  UPPER(TRIM(LOAN_STATUS)) AS LOAN_STATUS,
  TRIM(COMPLAINT_ID) AS COMPLAINT_ID,
  TRIM(COMPLAINT_CATEGORY) AS COMPLAINT_CATEGORY,
  UPPER(TRIM(COMPLAINT_PRIORITY)) AS COMPLAINT_PRIORITY,
  UPPER(TRIM(COMPLAINT_STATUS)) AS COMPLAINT_STATUS

FROM source_data

QUALIFY ROW_NUMBER() OVER (PARTITION BY TRANSACTION_ID ORDER BY _LOADED_AT DESC) = 1